// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const SUBMIT_VEHICLE_PHOTOS = "SUBMIT_VEHICLE_PHOTOS";
export const SUBMIT_VEHICLE_PHOTOS_SUCCESS = "SUBMIT_VEHICLE_PHOTOS_SUCCESS";
export const SUBMIT_VEHICLE_PHOTOS_FAIL = "SUBMIT_VEHICLE_PHOTOS_FAIL";
export const SUBMIT_VEHICLE_DETAILS = "SUBMIT_VEHICLE_DETAILS";
export const SUBMIT_VEHICLE_DETAILS_SUCCESS = "SUBMIT_VEHICLE_DETAILS_SUCCESS";
export const SUBMIT_VEHICLE_DETAILS_FAIL = "SUBMIT_VEHICLE_DETAILS_FAIL";
export const SUBMIT_VEHICLE_INSPECTION = "SUBMIT_VEHICLE_INSPECTION";
export const SUBMIT_VEHICLE_INSPECTION_SUCCESS = "SUBMIT_VEHICLE_INSPECTION_SUCCESS";
export const SUBMIT_VEHICLE_INSPECTION_FAIL = "SUBMIT_VEHICLE_INSPECTION_FAIL";
export const SUBMIT_WORK_NEED = "SUBMIT_WORK_NEED";
export const SUBMIT_WORK_NEED_SUCCESS = "SUBMIT_WORK_NEED_SUCCESS";
export const SUBMIT_WORK_NEED_FAIL = "SUBMIT_WORK_NEED_FAIL";
export const SUBMIT_SCHEMA_INSPECTION = "SUBMIT_SCHEMA_INSPECTION";
export const SUBMIT_SCHEMA_INSPECTION_SUCCESS = "SUBMIT_SCHEMA_INSPECTION_SUCCESS";
export const SUBMIT_SCHEMA_INSPECTION_FAIL = "SUBMIT_SCHEMA_INSPECTION_FAIL";
export const SUBMIT_COMMENTS = "SUBMIT_COMMENTS";
export const SUBMIT_COMMENTS_SUCCESS = "SUBMIT_COMMENTS_SUCCESS";
export const SUBMIT_COMMENTS_FAIL = "SUBMIT_COMMENTS_FAIL";


export const GET_CAR_MAKES = "GET_CAR_MAKES";
export const GET_CAR_MAKES_SUCCESS = "GET_CAR_MAKES_SUCCESS";
export const GET_CAR_MAKES_FAIL = "GET_CAR_MAKES_FAIL";

export const GET_CAR_MODELS = "GET_CAR_MODELS";
export const GET_CAR_MODELS_SUCCESS = "GET_CAR_MODELS_SUCCESS";
export const GET_CAR_MODELS_FAIL = "GET_CAR_MODELS_FAIL";

export const TOOGLE_ACTIVE_STEP = "TOOGLE_ACTIVE_STEP";