// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const SUBMIT_VEHICLE_PHOTOS = "SUBMIT_VEHICLE_PHOTOS";
export const SUBMIT_VEHICLE_PHOTOS_SUCCESS = "SUBMIT_VEHICLE_PHOTOS_SUCCESS";
export const SUBMIT_VEHICLE_PHOTOS_FAIL = "SUBMIT_VEHICLE_PHOTOS_FAIL";

